title: blog.lesis.lat
description: Laboratory of Engineering Studies in Information Security
url: https://blog.lesis.lat
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# header: large
sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Laboratory of Engineering Studies in Information Security
      url: /index.html
social:
    github: instriq
    twitter: lesis_lat
    email: contact@lesis.lat
    linkedin: company/lesis-group

google_analytics: ""
