title: LESIS
description: Laboratory of Engineering Studies in Information Security
url: https://blog.lesis.lat
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
social:
    github: instriq
    twitter: lesis_lat
    email: contact@lesis.lat
    linkedin: company/lesis-group

google_analytics: "UA-58263416-1"